name: SBOM Generation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Firefly SBOM Tool
      run: |
        pip install -e .
    
    - name: Run SBOM Scan
      run: |
        firefly-sbom scan --path . --format all --audit --output sbom-report
    
    - name: Upload SBOM Reports
      uses: actions/upload-artifact@v3
      with:
        name: sbom-reports
        path: sbom-report*
        retention-days: 30
    
    - name: Check for Critical Vulnerabilities
      run: |
        firefly-sbom scan --path . --audit || true
    
    - name: Create Issue for Vulnerabilities
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Critical vulnerabilities found in dependencies',
            body: 'SBOM scan detected critical vulnerabilities. Check the workflow artifacts for details.',
            labels: ['security', 'dependencies']
          })
