name: SBOM Generation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Firefly SBOM Tool
      run: |
        pip install -e .
    
    - name: Run SBOM Scan
      run: |
        firefly-sbom scan --path . --format all --audit --output sbom-report
    
    - name: Upload SBOM Reports
      uses: actions/upload-artifact@v4
      with:
        name: sbom-reports
        path: sbom-report*
        retention-days: 30
    
    - name: Build Vulnerability Summary
      id: vuln_summary
      shell: bash
      run: |
        python - <<'PY'
        import json
        import os
        import hashlib
        from pathlib import Path
        from firefly_sbom.core import SBOMGenerator
        
        gen = SBOMGenerator()
        data = gen.scan_repository(Path('.'), audit=True)
        vulns = data.get('vulnerabilities', [])
        # Normalize fields and compute severity counts
        counts = {k: 0 for k in ['critical','high','medium','low','unknown']}
        crit_ids = []
        for v in vulns:
            sev = (v.get('severity') or 'unknown').lower()
            counts[sev] = counts.get(sev, 0) + 1
            # Ensure presence of keys
            v['id'] = v.get('id') or v.get('cve') or v.get('ghsa') or 'UNKNOWN'
            v['component'] = v.get('component', 'Unknown')
            v['component_version'] = v.get('component_version', '')
            v['cvss_score'] = v.get('cvss_score', '')
            v['description'] = (v.get('description') or v.get('summary') or '')[:500]
            v['references'] = v.get('references') or []
            if sev == 'critical':
                crit_ids.append(v['id'])
        summary = {
            'total': len(vulns),
            'by_severity': counts,
            'vulnerabilities': vulns,
        }
        Path('sbom-vuln-summary.json').write_text(json.dumps(summary, indent=2))
        
        # Stable fingerprint from sorted critical IDs
        crit_ids.sort()
        fp_src = ('|'.join(crit_ids)).encode('utf-8')
        fingerprint = hashlib.sha256(fp_src).hexdigest() if crit_ids else ''
        
        # Build a detailed Markdown body
        title = 'Critical vulnerabilities detected in dependencies'
        lines = []
        lines.append(f'# 🚨 {title}')
        if fingerprint:
            lines.append(f'<!-- vuln-fingerprint: {fingerprint} -->')
        lines.append('')
        lines.append('This issue was created automatically from the SBOM security audit. It includes a summary and detailed list of detected vulnerabilities.')
        lines.append('')
        lines.append('## Summary')
        lines.append(f"- Total: {summary['total']}")
        lines.append(f"- Critical: {summary['by_severity'].get('critical',0)} | High: {summary['by_severity'].get('high',0)} | Medium: {summary['by_severity'].get('medium',0)} | Low: {summary['by_severity'].get('low',0)} | Unknown: {summary['by_severity'].get('unknown',0)}")
        lines.append('')
        lines.append('## Top Issues')
        lines.append('')
        lines.append('| ID | Severity | Component | Version | CVSS | Description | References |')
        lines.append('|---|---|---|---|---|---|---|')
        # Sort by severity and CVSS if present
        sev_order = {'critical':0,'high':1,'medium':2,'low':3,'unknown':4}
        def keyfn(v):
            s = sev_order.get((v.get('severity') or 'unknown').lower(), 4)
            try:
                c = float(v.get('cvss_score') or 0)
            except Exception:
                c = 0.0
            return (s, -c)
        for v in sorted(vulns, key=keyfn)[:50]:
            refs = v.get('references') or []
            refs_md = ' '.join(f"[link]({r})" for r in refs[:3])
            desc = (v.get('description') or '').replace('\n',' ').replace('|','\|')
            if len(desc) > 180:
                desc = desc[:180] + '…'
            lines.append(f"| {v.get('id')} | {v.get('severity','UNKNOWN').upper()} | {v.get('component')} | {v.get('component_version','')} | {v.get('cvss_score','')} | {desc} | {refs_md} |")
        
        md = '\n'.join(lines)
        Path('sbom-vuln-issue.md').write_text(md)
        
        # Set outputs for conditional issue creation
        has_crit = summary['by_severity'].get('critical',0) > 0
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            fh.write(f"has_critical={'true' if has_crit else 'false'}\n")
            fh.write(f"issue_title={title}\n")
        PY
    
    - name: Upsert Vulnerability Issue
      if: steps.vuln_summary.outputs.has_critical == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const title = process.env.ISSUE_TITLE || core.getInput('issue_title') || 'Critical vulnerabilities detected in dependencies';
          const body = fs.readFileSync('sbom-vuln-issue.md', 'utf8');
          // Find existing open issue with same title
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'security,dependencies,automated',
            per_page: 100
          });
          const existing = issues.find(i => i.title === title);
          if (existing) {
            core.info(`Updating existing issue #${existing.number}`);
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: existing.number,
              body
            });
          } else {
            core.info('Creating new vulnerability issue');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['security', 'dependencies', 'automated']
            });
          }
      env:
        ISSUE_TITLE: ${{ steps.vuln_summary.outputs.issue_title }}
    
    - name: Close Vulnerability Issue if Resolved
      if: steps.vuln_summary.outputs.has_critical != 'true'
      uses: actions/github-script@v6
      with:
        script: |
          const title = 'Critical vulnerabilities detected in dependencies';
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'security,dependencies,automated',
            per_page: 100
          });
          const existing = issues.find(i => i.title === title);
          if (existing) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: existing.number,
              body: '✅ No critical vulnerabilities detected in the latest scan. Closing this issue.'
            });
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: existing.number,
              state: 'closed'
            });
          }
